language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Kpax3");'
  - julia --check-bounds=yes -e 'Pkg.test("Kpax3", coverage=true);'
after_success:
  - julia -e 'cd(Pkg.dir("Kpax3")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder());'
